### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by jogibear9988** [wegel/fluentprotobufnet#1]
@wegel 
I'd like to fork your code, allow netcore and create a nuget.

Whats the Licence? MIT?

**Comment by wegel** [comment]
You can certainly go ahead, fork, and modify, use and reuse as you wish.
I'll try to update the repo with a licence, but yeah MIT should be alright.
Thanks!
-- 
Simon Labrecque

**Comment by jogibear9988** [comment]
thanks.

alread done: https://github.com/dotnetprojects/fluentprotobufnet
